# Generated by Django 4.2.7 on 2024-02-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_address_alter_profile_phonenumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coverImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/', verbose_name='Cover Image'),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='userImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/', verbose_name='Profile Image'),
        ),
    ]
