# Generated by Django 4.2.7 on 2024-02-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_coverimage_profile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('SUPPLIER', 'Supplier/Partner'), ('CLIENT', 'Consumer/Customer')], default='CLIENT', max_length=10),
        ),
    ]
