# Generated by Django 4.2.7 on 2024-02-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hakikaservices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='serviceImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/', verbose_name='Product Image1'),
        ),
    ]
